/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include "clock_config.h"

void System_Clock_Config(void);

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	while(1)
	{

	}
}

void System_Clock_Config(void)
{
	Clock_ConfigSetTypeDef config = {0};
	SET_BIT(RCC->APB1ENR, RCC_APB1ENR_PWREN);
	MODIFY_REG(PWR->CR1, PWR_CR1_VOS, PWR_CR1_VOS);

	config.HSE_SET.HSE_STATE = HSE_ON;
	config.HSI_SET.HSI_STATE = HSI_OFF;
	config.PLL_SET.PLL_STATE = PLL_ON;
	config.PLL_SET.PLLSRC = PLLSRC_HSE;
	config.PLL_SET.PLLM = 12;
	config.PLL_SET.PLLN = 216;
	config.PLL_SET.PLLP = 0;
	config.PLL_SET.PLLQ = 9;

}

void Error_Handler(void)
{
	__disable_irq();
	while(1);
}
