/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include "stm32f723xx.h"

void System_Clock_Config(void);

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	while(1)
	{

	}
}

void System_Clock_Config(void)
{
	RCC->CR |= RCC_CR_HSEON;
	RCC->CR &= ~RCC_CR_HSEBYP;

	while(!RCC->CR & RCC_CR_HSERDY);

	RCC->CR &= ~RCC_CR_PLLON;
	RCC->PLLCFGR = RCC_PLLCFGR_PLLSRC_HSE|
			(0x0c<<RCC_PLLCFGR_PLLM_Pos)|
			((0xd8<<6)<<RCC_PLLCFGR_PLLN_Pos)|
			(0x00<<RCC_PLLCFGR_PLLP_Pos)|
			(0x09<<RCC_PLLCFGR_PLLQ_Pos);

}
